// Edit lessons and questions here. `c` is the index of the correct option (0-3).
export const LESSONS = [
  { t: 'Lesson 1: What Plants Need', d: '☀️ + 💧 + 🌫️ CO₂', x: 'Photosynthesis is how plants make their own food. They need three inputs: sunlight (energy), water (absorbed by roots) and carbon dioxide (CO₂, taken in from air through tiny leaf holes called stomata).' },
  { t: 'Lesson 2: The Green Factory', d: '🍃 → chloroplast → chlorophyll', x: 'Photosynthesis happens inside chloroplasts in leaf cells. They contain chlorophyll, a green pigment that absorbs light energy (mostly red and blue light) and reflects green, which is why leaves look green.' },
  { t: 'Lesson 3: What Plants Make', d: '🍬 glucose + 🫧 oxygen', x: 'Using light energy, the plant turns water and CO₂ into glucose (sugar food for growth and energy) and releases oxygen as a by-product. Equation: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.' },
  { t: 'Lesson 4: Light & Rate', d: '☀️↑ rate ↑   🌑 rate ↓', x: 'The rate of photosynthesis depends on conditions. More light, more CO₂ and a suitable temperature speed it up. Without light, photosynthesis stops, and the plant must use its stored glucose until it runs out.' },
];
export const QS = [
  { q: 'A plant sits in a sealed, transparent jar with plenty of water and bright light, but all the carbon dioxide has been removed. What is most likely to happen?', o: ['It makes more oxygen than usual', 'It cannot make glucose, because a key raw material is missing', 'It makes glucose using oxygen instead', 'Nothing changes, because light alone is enough'], c: 1, e: 'CO₂ is a raw material. Without it, glucose cannot be made.' },
  { q: 'A scientist grows a plant under only green light. The plant grows poorly. Which explanation best fits what you learned?', o: ['Chlorophyll absorbs green light very strongly', 'Roots stop taking in water in green light', 'Plants cannot use any light that is coloured', 'Chlorophyll reflects most green light, so little energy is absorbed'], c: 3, e: 'Chlorophyll reflects green light, so little energy is captured for photosynthesis.' },
  { q: 'A student places a healthy water plant in sunlight and sees bubbles rising from its leaves. Which gas are the bubbles mostly made of?', o: ['Oxygen, released as a by-product', 'Carbon dioxide, released as waste', 'Hydrogen, split from the water', 'Nitrogen, taken from the soil'], c: 0, e: 'Oxygen is the by-product of photosynthesis, released when light is available.' },
  { q: 'A houseplant is moved from a sunny window into a dark cupboard for two weeks. What will most likely happen?', o: ['It makes more glucose in the dark to save energy', 'It switches to making oxygen only', 'Photosynthesis stops, it uses stored food and becomes weak', 'It grows faster because it is cooler'], c: 2, e: 'Without light, photosynthesis stops. The plant uses stored glucose until it runs out.' },
];
